#! /bin/bash

echo "Sample Shells check run using loop.. "

for check_for in sh bash ksh csh tcsh zsh
do
cmd="$check_for -c exit"
if ( $cmd > /dev/null 2>/dev/null )
then
echo $check_for " found "
else
echo $check_for  " not found "
fi
done
exit 0

