#!/bin/bash

echo "Script Begin"
function func
{
	
	count=$#
	index=0
	for var in $@
	do

		echo $var
		if [ $? -eq 0 ]
		then
			index=$[ $index + 1 ]
		fi

	done
	if [ $index -eq $count ]
	then
		echo "Function was successfull"
	else		
		ec
	fi


}
func 34 23 87
echo "The return value or status of the last command of the function is $?"


echo "Script End"

exit 0
