#!/bin/bash

read -p "Enter the number: " number
if [ $number -gt 0 ] && [ $number -lt 10 ]
then
	echo "The number is single digit positive number. "
else
	echo "The number is either non-positive or not a single-digit number"
fi

exit 0
