#!/bin/bash
read -p "Enter first Number: " num1
read -p "Enter second Number: " num2
echo "First Number: $num1" 
echo "Second Number: $num2" 

if [ $num1 -eq $num2 ]
then
	echo "Both the numbers are equal"
fi

if [ $num1 -ge $num2 ]
then
	echo "$num1 is greater than or equal $num2."
fi

if [ $num1 -gt $num2 ]
then
	echo "$num1 is greater than $num2. "
fi

if [ $num1 -le $num2 ]
then
	echo "$num1 is less than or equal to $num2."
fi

if [ $num1 -lt $num2 ]
then
	echo "$num1 is less than $num2."
fi

if [ $num1 -ne $num2 ]
then
	echo "$num1 is not equal to $num2".

fi

exit 0
