#!/bin/bash

read -p "Enter the first number: " num1
read -p "Enter the second number: " num2

if [ $num1 -gt $num2 ]
then
	echo "$num1 is greater than $num2."

elif [ $num1 -lt $num2 ]
then
	echo "$num1 is lesser than $num2."
else
	echo "$num1 is equal to $num2."
fi

exit 0

	
