#!/bin/bash

echo "task starts"
matrix=(
	"1 2 3"
	"4 5 6"
	"7 8 9"
)
row=0
while [ $row -lt ${#matrix[@]} ]
do
	row_elements=(${matrix[$row]})
	col=0
	
	while [ $col -lt ${#row_elements[@]} ]
	do
		echo "Value at index [$row,$col]:${row_elements[$col]}"
		col=$((col + 1))
	done
	row=$((row + 1))	
done

echo "task ends"

exit 0
