#!/bin/bash

echo "task starts"

echo "2 is a prime number."

for((num=2;num <= 50;num++))
do
start=2
#although sqrt/(num/2) can be taken as limit

limit=$((num-1))
	
	while [ $start -le $limit ]
	do
		if [ $(($num % $start)) -eq 0 ] 
		then
		break;
		fi
		if [ $start -eq $limit ] 
		then
			break;
		fi
		start=$((start +1))
	done
	if [ $start -eq $limit ]
	then
		echo "$num is a prime number."
	fi
done

echo "task ends"

exit 0
