#!/bin/bash

echo "This is the log script , it will log all the activites related to rcs"

logFileName=log_`date +%d%m%y`

touch $logFileName

#using for loop for now
#rlog *.h,v >> $logFileName
#rlog *.c,v >> $logFileName

for file in $( ls *h,v ) $( ls *c,v )
do
rlog $file >> $logFileName 
done

echo "Exiting from the log script for now"
exit 0

