#!/bin/bash
#: This script will take care of checkin all the related files and creating executable out of them.
#: This will run the final executable as well.
#: This will also checkout all the related files for further modification.

#read -n1 -p "Do you want to check in the files(y/n)"
read -p "Do you want to check in the files(y/n)"
if [ $REPLY = y ]
then

	# using for loop

	echo "Checkin all the headers files "
	#ci *.h
	for file in $( ls *h )
	do
	ci $file
	done

	echo "Checkin all source files "
	for file in $( ls *c ) 
	do
	ci $file
	done
	#ci *.c

	echo "Checkin Make file "
	#ci Makefile
	for mf in Makefile
	do
	ci $mf
	done


fi

read -p "Do you want to build(y,n)"
if [ $REPLY = y ]
then
	echo "Checkout all the header files for Make file  Compilation in read mode. "
	# using for loop for below case
	#co *.h,v

	for file in $( ls *h,v )
	do
	co $file
	done

	echo "Checkout all the source files for Make file compilation in read mode. "
	#co *.c,v

	for file in $( ls *.c,v )
	do
	co $file
	done

	echo "Checkout Makefile in read mode."
	co Makefile

	echo "Cleaning old obj's and exectuables "
	make clean

	echo "Running Make to build all object files and executable mdcaeuit as the final result "
	make

fi

read -p "Do you want to run the project(y,n)" 

if [ $REPLY = y ]
then


	echo "Now we are running the executable "
	./mdcaeuit

fi

read  -p "Do you want to check out the files(y,n)"

if [ $REPLY = y ]
then


	echo "Now starting the process of checking out all the files in read/write mode. "

	echo "Checking out all the header files one by one "
	#co -l *.h,v
	#using for loop for above task
	for file in `ls *h,v`
	do
	co -l $file
	done

	echo "Checking out all the source files one by one "
	#co -l *.c,v

	for file in $( ls *.c,v )
	do
	co -l $file
	done

	echo "Checking out the Makefile "
	co -l Makefile

fi
echo "Exiting the script now..."

exit 0



